config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit] do
    member do
      get :followings
      get :followers
      get :likes
      post :edit
      delete :destroy
      patch :update
    end 
  end
  
  resources :microposts, only: [:create, :destroy, :edit, :show] do
    member do
      post :likes, to: 'likes#create'
      delete :unlikes, to: 'likes#destroy'
      post :edit
      get :show
      patch :update
    end 
  end
  
  resources :relationships, only: [:create,:destroy]
  resources :likes, only: [:create,:destroy] 
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email,presence: true, length: { maximum: 255},
                  format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                  uniqueness: { case_sensitive: false }
  has_secure_password
  
  mount_uploader :picture, PictureUploader
  
  has_many :microposts,dependent: :destroy
  
  has_many :relationships,dependent: :destroy
  has_many :followings, through: :relationships, source: :follow,dependent: :destroy
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user,dependent: :destroy

  has_many :likes,dependent: :destroy
  has_many :like_microposts, through: :likes, source: :micropost
  

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end 
  end 
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end 
  
  def following?(other_user)
    self.followings.include?(other_user)
  end 
  
  def feed_microposts
    Micropost.where(user_id: self.following_ids + [self.id])
  end 
  
  def like(other_micropost)
    self.likes.find_or_create_by(micropost_id: other_micropost.id)
  end 
  
  def unlike(other_micropost)
    like = self.likes.find_by(micropost_id: other_micropost.id)
    like.destroy if like
  end 
  
  def like?(other_micropost)
    self.like_microposts.include?(other_micropost)
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in,only:[:index,:show,:followings,:followers,:likes]
  # before_action :correct_user,only:[:edit]
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.order('created_at DESC').page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザーを登録しました'
      redirect_to @user
    else
      flash[:danger] = 'ユーザーの登録に失敗しました'
      render :new
    end
  end 
  
  def edit 
    @user = User.find(params[:id])
  end 
  
  def update 
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:success] = 'ユーザー情報を更新しました'
      redirect_to @user
    else 
      flash.now[:danger] = 'ユーザー情報の更新に失敗しました'
      render :edit
    end
  end 
  
  def destroy 
    @user = User.find_by(id: params[:id])
    @microposts = Micropost.find_by(user_id: params[:id])
    flash[:success] = "ユーザーを削除しました"

    if @microposts.nil?
      @user.destroy
      redirect_to("/")
    else
      @microposts.destroy
      @user.destroy
      redirect_to("/")
    end
  end 
      
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end 
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end 
  
  def likes
    @user = User.find(params[:id])
    @likes = @user.likes.page(params[:page])
    @microposts = @user.like_microposts.order('created_at DESC').page(params[:page])
    counts(@user)
  end 
  
  private 

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:age,:gender,:picture)
  end 
  
  # def correct_user
  #   @user = current_user
  #   unless @user
  #   redirect_to root_url
  #   end 
  # end 
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, option = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = option[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mp"
  end 
end

app/views/users/_users.html.erb
<% if users.any? %>
  <ul>
    <% users.each do |user|%>
      <li class="media">
        <div class="media-left">
         <% if user.picture.file.nil? %>
            <img class="media-object img-rounded" src="<%= gravatar_url(user, {size: 50})%>" alt="">
          <% else %>
            <%= image_tag(user.picture.url, size: 50) %>
          <% end %>
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'view profile', user_path(user) %></p>
          </div>
        </div>
      </li>
      <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<% if current_user == @user %>

 <h1><%= @user.name %> のユーザー情報</h1>


    <%= form_for(@user) do |f| %>
      <div class="form-group">
        <%= f.label :name, 'Name'%>
        <%= f.text_field :name,class: 'form-control', style: 'width: 200px; display:inline;'%>
      </div>
    
      <div class="form-group">
        <%= f.label :age, 'Age'%>
        <%= f.select :age, [["", ""],["20代", "20代"], ["30代", "30代"],  ["40代", "40代"], ["50代以上", "50代"],["60代以上", "60代以上"] ],class: 'form-control' %>
      </div>
    
      <div class="form-group">
        <%= f.label :gender, 'Gender'%>
        <label>
          <%= f.radio_button :gender, "男性" %> 男性</label>
        <label>
          <%= f.radio_button :gender, "女性"%> 女性</label>
      </div>
    
      <div class="form-group">
        <%= f.label :picture, 'Thumbnail'%>
        <%= f.file_field :picture %>
      </div>

      <%= f.submit '更新', class: 'btn btn-default' %>
    <% end %>
    <br>
  <%= link_to 'ユーザーに戻る', @user , class: 'btn btn-primary' %>
  
  <%= link_to '退会する', user_path(@user), method: :delete, data: {confirm: 'You sure?'}, class: 'btn btn-danger' %>
  
<% end %>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <% if @user.picture.file.nil? %>
          <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 })%>" alt="">
        <% else %>
          <%= image_tag(@user.picture.url, size: 300) %>
        <% end %>
      </div>
      <div class="panel-footer text-center"> 
        <p>年齢：<%= @user.age %></p>
        <p>性別：<%= @user.gender %></p>
        <% if current_user == @user %>
        <%= link_to 'edit', edit_user_path(@user), class: 'btn btn-primary'%>
        <% end %>
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user))%>"><%= link_to user_path(@user) do %>Microposts <span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user))%>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user))%>"><%= link_to followers_user_path(@user) do %>Followers<span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(likes_user_path(@user))%>"><%= link_to likes_user_path(@user) do %>Likes<span class="badge"><%= @count_likes %></span><% end %></li>    
    </ul>
    <%= render 'users', users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <% if @user.picture.file.nil? %>
          <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 })%>" alt="">
        <% else %>
          <%= image_tag(@user.picture.url, size: 300) %>
        <% end %>
      </div>
      <div class="panel-footer text-center"> 
        <p>年齢：<%= @user.age %></p>
        <p>性別：<%= @user.gender %></p>
        <% if current_user == @user %>
        <%= link_to 'edit', edit_user_path(@user), class: 'btn btn-primary'%>
        <% end %>
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user))%>"><%= link_to user_path(@user) do %>Microposts <span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user))%>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user))%>"><%= link_to followers_user_path(@user) do %>Followers<span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(likes_user_path(@user))%>"><%= link_to likes_user_path(@user) do %>Likes<span class="badge"><%= @count_likes %></span><% end %></li>
    </ul>
    <%= render 'users', users: @followings %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/likes.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <% if @user.picture.file.nil? %>
          <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 })%>" alt="">
        <% else %>
          <%= image_tag(@user.picture.url, size: 300) %>
        <% end %>
      </div>
      <div class="panel-footer text-center"> 
        <p>年齢：<%= @user.age %></p>
        <p>性別：<%= @user.gender %></p>
        <% if current_user == @user %>
        <%= link_to 'edit', edit_user_path(@user), class: 'btn btn-primary'%>
        <% end %>
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user))%>"><%= link_to user_path(@user) do %>Microposts <span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user))%>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user))%>"><%= link_to followers_user_path(@user) do %>Followers<span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(likes_user_path(@user))%>"><%= link_to likes_user_path(@user) do %>Likes<span class="badge"><%= @count_likes %></span><% end %></li>
    </ul>
    <%= render  'microposts/microposts', microposts: @microposts %>
  </div>
</div>

app/views/users/new.html.erb
<%= form_for(@user) do |f|%>
  <%= render 'layouts/error_messages', model: f.object %>
<% end %>

<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |f|%>
    
    <div class="form-group">
      <%= f.label :name, 'Name'%>
      <%= f.text_field :name,class: 'form-control'%>
    </div>
    
    <div class="form-group">
      <%= f.label :email, 'Email'%>
      <%= f.email_field :email,class: 'form-control'%>
    </div>
    
    <div class="form-group"  style="display: inline-block; margin: 20px 0 20px 0;">
      <%= f.label :age, 'Age'%>
      <%= f.select :age, [["",""],["20代", "20代"], ["30代", "30代"],  ["40代", "40代"], ["50代以上", "50代"],["60代以上", "60代以上"] ],class: 'form-control' %>
    </div>
    
    <div class="form-group" style="display: inline-block; margin-left: 30px;">
      <%= f.label :gender, 'Gender'%>
      <label>
        <%= f.radio_button :gender, "男性" %> 男性</label>
        <label>
        <%= f.radio_button :gender, "女性"%> 女性</label>
    </div>
    
    <div class="form-group"  style="display: inline-block; margin: 20px 0 20px 0;">
      <%= f.label :picture, 'Thumbnail'%>
       <%= f.file_field :picture %>
    </div>
    
    <div class="form-group">
      <%= f.label :password, 'Password'%>
      <%= f.password_field :password,class: 'form-control'%>
    </div>
    
    <div class="form-group">
      <%= f.label :password_confirmation, 'Confirmation'%>
      <%= f.password_field :password_confirmation,class: 'form-control'%>
    </div>
    
    <%= f.submit 'Sign up', class: 'btn btn-primary btn-block'%>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <% if @user.picture.file.nil? %>
          <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 })%>" alt="">
        <% else %>
          <%= image_tag(@user.picture.url, size: 300) %>
        <% end %>
      </div>
      <div class="panel-footer text-center"> 
        <p>年齢：<%= @user.age %></p>
        <p>性別：<%= @user.gender %></p>
        <% if current_user == @user %>
        <%= link_to 'edit', edit_user_path(@user), class: 'btn btn-primary'%>
        <% end %>
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user))%>"><%= link_to user_path(@user) do %>Microposts <span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user))%>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user))%>"><%= link_to followers_user_path(@user) do %>Followers<span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(likes_user_path(@user))%>"><%= link_to likes_user_path(@user) do %>Likes<span class="badge"><%= @count_likes %></span><% end %></li>
    </ul>
    <%= render 'microposts/microposts', microposts: @microposts %>
  </div>
</div>