config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit] do
    member do
      get :followings
      get :followers
      get :likes
      post :edit
      delete :destroy
      patch :update
    end 
  end
  
  resources :microposts, only: [:create, :destroy, :edit, :show] do
    member do
      post :likes, to: 'likes#create'
      delete :unlikes, to: 'likes#destroy'
      post :edit
      get :show
      patch :update
    end 
  end
  
  resources :relationships, only: [:create,:destroy]
  resources :likes, only: [:create,:destroy] 
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :content, presence: true,length: { maximum: 255 }
  
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
end 

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user,only:[:destroy,:edit,:show]
  def create
    @micropost = current_user.microposts.build(micropost_params)
     if @micropost.save
       flash[:success] = 'メッセージを投稿しました'
       redirect_to root_url
     else
       @microposts = current_user.feed_microposts.order('created_at DESC').page(params[:page])
       flash.now[:danger] = 'メッセージの投稿に失敗しました'
       render 'toppages/index'
     end 
  end

  def destroy
    @micropost.destroy
    flash[:success] = 'メッセージを削除しました'
    redirect_back(fallback_location: root_path)
  end
  
  def edit 
    @micropost = Micropost.find(params[:id])
  end 
  
  def update 
    @micropost = Micropost.find(params[:id])

    if @micropost.update(micropost_params)
      flash[:success] = 'Micropost は正常に更新されました'
      redirect_to @micropost
    else
      flash.now[:danger] = 'Micropost は更新されませんでした'
      render :edit
    end
  end 
  
  def show 
    @micropost = Micropost.find(params[:id])
  end
  
  private
  
  def micropost_params
    params.require(:micropost).permit(:content)
  end 
  
  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    unless @micropost
    redirect_to root_url
    end 
  end 
end

app/views/microposts/_microposts.html.erb
<ul class="media-left">
  <% microposts.each do |micropost|%>
  <li class="media">
    <div class="media-left">
      <% if micropost.user.picture.file.nil? %>
            <img class="media-object img-rounded" src="<%= gravatar_url(micropost.user, {size: 50})%>" alt="">
          <% else %>
            <%= image_tag(micropost.user.picture.url, size: 50) %>
          <% end %>
    </div>
    <div class="media-body">
      <div>
        <%= link_to micropost.user.name, user_path(micropost.user)%><span  class="text-muted" > posted at <%= micropost.created_at %></span>
      </div>
      <div>
        <p><%= micropost.content %></p>
      </div>
      <div>
         <% if current_user.like?(micropost) %>
            <%= link_to 'unlike', unlikes_micropost_url(micropost) , method: :delete, class: 'btn btn-default btn-xs'%>
         <% else %>
            <%= link_to 'like', likes_micropost_url(micropost) , method: :post, class: 'btn btn-warning btn-xs' %>
        <% end %>
        <% if current_user == micropost.user %>
        <%= link_to 'Delete', micropost, method: :delete, data: {confirm: 'You sure?'}, class: 'btn btn-danger btn-xs' %>
        <%= link_to 'detail', micropost, class: 'btn btn-primary btn-xs'%>
        <% end %>
      </div>
    </div>
  </li>
  <% end %>
  
  <%= paginate microposts %>
  
</ul>

app/views/microposts/edit.html.erb
<h1>id: <%= @micropost.id %> の投稿編集ページ</h1>

<%= form_for(@micropost) do |f| %>
  <%= f.label :content, '投稿' %>
  <%= f.text_field :content,class: 'form-control', style: 'width: 200px; display:inline;' %>

  <%= f.submit '更新', class: 'btn btn-default' %>
<% end %>
<br>
<%= link_to '一覧に戻る', root_url , class: 'btn btn-primary' %>

app/views/microposts/show.html.erb
<h1>id: <%= @micropost.id %> の投稿詳細ページ</h1>

<table class="table table-bordered" >
  <thead>
    <tr>
      <th>ID</th>
      <th>コンテンツ</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @micropost.id %></td>
      <td><%= @micropost.content %></td>
    </tr>
  </tbody>
</table>

<%= link_to '編集', edit_micropost_path(@micropost), method: :post, class: 'btn btn-primary'%>